matrix:
  IMAGE: 
    # r-hub/containers ubuntu-release
    - ghcr.io/r-hub/containers/ubuntu-release

when:
  - branch: main
    event: push
  - event: pull_request
  - event: tag

variables:
  r_site_config: &r_site_config
    - cat /etc/os-release >> $(R RHOME)/etc/Renviron.site
    - |
      cat << END >> $(R RHOME)/etc/Rprofile.site
      options(
        Ncpus = 4,
        repos = c(
          P3M = sprintf(
            "https://p3m.dev/cran/__linux__/%s/latest",
            if (nchar(envvar <- Sys.getenv("VERSION_CODENAME"))) envvar
          ),
          CRAN = "https://cloud.r-project.org"
        ),
        pak.sysreqs = TRUE,
        cli.dynamic = FALSE,
        cli.default_num_colors = 256,
        crayon.enabled = TRUE
      )

      cache_path <- file.path("$${PWD}", ".woodpecker", "r-cache-lib")
      if (!dir.exists(cache_path)) dir.create(cache_path, recursive = TRUE)

      .libPaths(cache_path, .libPaths())
      END    

steps:
  - name: setup environment
    image: ${IMAGE}
    pull: true
    commands:
      - <<: *r_site_config
      - |
        R -q -s --no-save << "END"
        pak_repo <- sprintf(
          "https://r-lib.github.io/p/pak/stable/%s/%s/%s",
          .Platform$pkgType,
          R.Version()$os,
          R.Version()$arch
        )

        install.packages("pak", repos = pak_repo)
        pak::local_install_dev_deps()
        END

  - name: check
    image: ${IMAGE}
    pull: true
    commands:
      - <<: *r_site_config
      - |
        R -q -s --no-save << "END"
        if (Sys.getenv("_R_CHECK_FORCE_SUGGESTS_", "") == "")
          Sys.setenv("_R_CHECK_FORCE_SUGGESTS_" = "false")

        if (Sys.getenv("_R_CHECK_CRAN_INCOMING_", "") == "")
          Sys.setenv("_R_CHECK_CRAN_INCOMING_" = "false")

        pak::pkg_install("rcmdcheck")
        rcmdcheck::rcmdcheck(
          args = c("--no-manual", "--as-cran"),
          build_args = c("--no-manual"),
          error_on = "warning",
          check_dir = "check"
        )
        END
